### ISSUE TITLE
version 0.0.2 SyntaxError: Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by temoto** [khalidhoffman/stylus-require-css-evaluator#2]
Thanks for the thing that is supposed to inline css stylus. I tried random code modification to use your plugin with gulp.

Any help is much appreciated.

> `gulpfile.js`
```js
'use strict';
// ...
gulp.task('stylus', () => {
  return gulp.src(['src/**/*.styl'])
    .pipe(stylus().use(require('stylus-require-css-evaluator')))
    .pipe(gulp.dest('build/'));
});
```

```
% gulp --version
[00:23:57] CLI version 3.9.1
[00:23:57] Local version 3.9.1

% npm --version
3.7.3

% node --version
v5.9.1

% fgrep styl package.json
    "gulp-stylus": "^2.5.0",
    "stylus-require-css-evaluator": "0.0.2",

% gulp
[00:18:16] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/temoto/dev/project/node_modules/stylus-require-css-evaluator/index.js:1:91)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by temoto** [comment]
With `node 7.5.0` the error becomes:

```
[00:34:32] TypeError: stylus(...).use is not a function
    at Gulp.gulp.task (/Users/temoto/dev/project/gulpfile.js:89:20)
    at module.exports (/Users/temoto/dev/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/temoto/dev/project/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/temoto/dev/project/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/temoto/dev/project/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by khalidhoffman** [comment]
I think you may just need to move `use: req...` to inside an object passed to stylus like this:
```
'use strict';
// ...
gulp.task('stylus', () => {
  return gulp.src(['src/**/*.styl'])
    .pipe(stylus({use: require('stylus-require-css-evaluator')})
    .pipe(gulp.dest('build/'));
});
```
This worked for me. 

As for your `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` error, I wasn't able to reproduce that. Your error stack doesn't make much sense to me either. Anyway, after some googling the best I can offer is an addition of the `"use strict"` tag. I just pushed the update to npm. Try updating and see if it works.

**Comment by temoto** [comment]
The object notation worked. Thank you.
